BEAM:
  ANGLE:
    MAX: 4.0
    MIN: -4.0
  ANGLE_SCALE: 10.0
COMM:
  BAUD_RATE: 115200
  DT: 0.02
  PORT: COM7
  UPDATE_RATE: 50.0
SENSOR:
  DISTANCE:
    BACKSTOP: 90
    BACKSTOP_MM: 0.09
    MID: 105
  OBSERVATION_SCALE: 0.01
  READING_SCALE: 0.01
SERVO:
  CMD:
    MAX: 2000
    MID: 1500
    MIN: 1000
    REST: 1550
  PWM_SCALE: 0.001
TIMEOUT:
  STEPS: 5
  TIME: 0.1
